import Header from '@/components/Header';
import '../globals.css';
import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[rgba(0,0,0,1)] bg-bg-image bg-cover bg-repeat">
        <div>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
